name: 'Helm Chart Release'
description: 'Packages Helm charts and uploads them to a Helm repo'
inputs:
  chart-path:
    description: 'Path to the Helm chart'
    required: true
  github-token:
    description: 'GitHub token for authentication'
    required: true
  helm-repo:
    description: 'GitHub repository (e.g., user/repo) for Helm charts'
    required: true
  helm-repo-folder:
    description: 'In which folder in the helm-repo to put the release'
    required: true
  branch-name:
    description: 'Name of the branch to deploy to'
    required: true
    default: master
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.chart-path }}
    - ${{ inputs.github-token }}
    - ${{ inputs.helm-repo }}
